#!/usr/bin/env bash
set -eu

version=0.10.0
tarball="shellcheck-v$version.linux.x86_64.tar.xz"
sha256=6c881ab0698e4e6ea235245f22832860544f17ba386442fe7e9d629f8cbedf87

check_version() {
	out="$(shellcheck --version 2>/dev/null)" && [[ "$out" = *"
version: $version
"* ]]
}

if ! check_version; then
	tmpdir="$(mktemp -d)"
	trap 'rm -r "$tmpdir"' EXIT
	cd "$tmpdir"
	wget -nv "https://github.com/koalaman/shellcheck/releases/download/v$version/$tarball"
	sha256sum -c <<<"$sha256 $tarball"
	tar -xJf "$tarball" --no-same-owner --strip-components=1 -C /usr/local/bin "shellcheck-v$version/shellcheck"
	check_version
fi
