#!/usr/bin/env zsh
# shellcheck disable=all

brew install python \
	wget \
	coreutils \
	node@20 \
	gcc \
	pkg-config \
	libpq \
	openssl \
	shellcheck \
	shfmt

echo 'export PATH="/opt/homebrew/opt/node@20/bin:$PATH"' >>~/.zshrc

# Reload shell

source ~/.zshrc

# Create virtual environment

python3 -m venv venv

if [ -d venv/bin ]; then
	source venv/bin/activate
fi

# Install npm packages

npm install

# Install python packages

pip install -r requirements/dev.txt
