[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
src_paths = [".", "src"]
profile = "black"
line_length = 100

[tool.aerich]
tortoise_orm = "app.settings.TORTOISE"
location = "./migrations"
src_folder = "./."
